# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: CI workflow for socialnetwork app
on:
  push:
    branches: [main]
jobs:
  compile:
    runs-on: ubuntu-latest
    name: Compile Social Network
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Compile code
        run:  |
              mvn compile
  test:
    runs-on: ubuntu-latest
    name: Running tests
    needs: compile
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'   
      - name: Run tests
        run: mvn test
        env: 
          SPRING_ACTIVE_PROFILE: "test"
  build:
    runs-on: ubuntu-latest
    name: Run mvn build and generate coverage report
    needs: test
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'      
      - name: Build with Maven
        run: mvn -B package --file pom.xml -Dmaven.test.skip=true    
        env:
          SPRING_ACTIVE_PROFILE: "prod"
        shell: bash
